#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2015-01-16 17:56:15 +0000 (Fri, 16 Jan 2015)
#
#  vim:ts=2:sw=2:et
#
FROM gambol99/embassy-service
MAINTAINER Rohith <gambol99@gmail.com>

ADD httpd.ini /etc/supervisord.d/httpd.ini

RUN yum install -y httpd
